name: .NET Test

on:
  push:
    branches: [ main ]

  workflow_dispatch:
      inputs:
        tag:
          description: Person to greet
          required: true
          default: Mona the Octocat
        name:
          description: another param
          required: true


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0
    - name: log .net version
      run: dotnet --version
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: |
        dotnet run
        dotnet build --no-restore
